### ISSUE TITLE
How to use the icons in the html template?

### ISSUE THREAD

**Issue by nilsi** [mage3k/vue-feather-icon#1]
Hi,

If I understand this correctly I can obtain an icon by:
`const ActivityIcon = require('vue-feather-icon/components/activity')`

How would I then use this? Should I set that as `src` for one of my `<img>` tags? Which then enables me to manipulate the icon (changing color, size etc with css)

Thanks.

**Comment by tthallos** [comment]
```
<template>
  <activity-icon></activity-icon>
</template>
<script>
const ActivityIcon = require('vue-feather-icon/components/activity')
export default {
  components: {
    ActivityIcon
  }
}
</script>
```

**Comment by nilsi** [comment]
Oh I see, its just template wrappers for the `<svg>` elements. Thanks
