### ISSUE TITLE
Uncaught TypeError: Cannot set property props of #<Object> which has only a getter

### ISSUE THREAD

**Issue by JeanBarriere** [mage3k/vue-feather-icon#10]
Hi,
I got the following error when I try to install the module:
`Uncaught TypeError: Cannot set property props of #<Object> which has only a getter`

I installed it globally using
```javascript
import VueFeatherIcon from 'vue-feather-icon'

Vue.use(VueFeatherIcon)
```

I use vue version `2.5.2`

**Comment by artiship** [comment]
The save error

**Comment by mcordoba** [comment]
Same here... any ideas?

**Comment by ChikuwaJB** [comment]
I fixed this error and sended pull request.
https://github.com/mage3k/vue-feather-icon/pull/11

**Comment by Quadriphobs1** [comment]
Still having this issue with vue:2.5.16

**Comment by bodinsamuel** [comment]
The issue is still present :'(

**Comment by MickaelBergem** [comment]
Poke @mage3k ? :)
Did you get time to review the PR @ChikuwaJB submitted?

**Comment by MatildaJin** [comment]
same error.

**Comment by Simon-Renault** [comment]
The issue is still here.

**Comment by lohitreddy08** [comment]
Is the issue solved??

**Comment by MickaelBergem** [comment]
I have been using a forked version that matches my needs, while allowing icon colors to be set via CSS classes (not fixed for all icons), if you are looking for a quick solution : https://github.com/MickaelBergem/vue-feather-icon

**Comment by julio-arcila** [comment]
I have the same problem

**Comment by tthallos** [comment]
this repo is no longer maintained, you can try [vue-feather-icons](https://github.com/egoist/vue-feather-icons)
