### ISSUE TITLE
icon doesn't exist

### ISSUE THREAD

**Issue by DedeBrahma** [mage3k/vue-feather-icon#15]
There are some icons doesn't exist
ex: dollar-sign, shopping-bag, etc

**Comment by MarcelloTheArcane** [comment]
https://feathericons.com/?query=dollar-sign and https://feathericons.com/?query=shopping-bag exist now

**Comment by tthallos** [comment]
this repo is no longer maintained, you can try [vue-feather-icons](https://github.com/egoist/vue-feather-icons)
