### ISSUE TITLE
Pass props to the components

### ISSUE THREAD

**Issue by MatiasOlivera** [mage3k/vue-feather-icon#17]
It would be nice to **pass properties to the components** to easily modify the _width_, _length_, _color_, etc. of the icons.

The props could be:

- `size (width / height): Number`
- `stroke: String`
- `stroke-width: Number`
- `stroke-linecap: String`
- `stroke-linejoin: String`

What do you think?

**Comment by hyperupcall** [comment]
This sounds like a great feature

**Comment by ThomasAndrewMacLean** [comment]
Will try to make a PR later today that implements this functionality.

**Comment by ThomasAndrewMacLean** [comment]
Hi, I was looking to implement this, but noticed you can already pass in props: 

        <zap-icon stroke-width="5" height="50" width="50" stroke="green" />
        <activity-icon stroke-width="5" height="50" width="50" stroke="red" />


![screen shot 2018-10-14 at 12 09 09](https://user-images.githubusercontent.com/31767869/46915724-adfc0000-cfaf-11e8-8aa9-36f64b03e071.png)

**Comment by MatiasOlivera** [comment]
@ThomasAndrewMacLean Good, I had forgotten that there were non-prop attributes.  [See the docs](https://vuejs.org/v2/guide/components-props.html#Non-Prop-Attributes)

**Comment by tthallos** [comment]
this repo is no longer maintained, you can try [vue-feather-icons](https://github.com/egoist/vue-feather-icons)
