### ISSUE TITLE
How to keep updated the component with newer feather icon?

### ISSUE THREAD

**Issue by ricardoa-vega-stori** [mage3k/vue-feather-icon#18]
Hello,
I was wondering if this vue component is going to include newer feather icons. If not, what's the process to create new ones? I'm not JS expert but I use the icons in almost all my projects. This is not a complain, I'm thankful this vue component exists, I just want to know how to keep it updated. Any directions would be welcome :) 

Thanks in advance @mage3k

**Comment by jalcine** [comment]
Glad I saw this. So it looks like the project itself pulls from a Git submodule. If instead of doing this, it relied on NPM's resolution of the `feather-icons` project; you could use whichever version you wanted.

**Comment by jalcine** [comment]
Looking closer, this does a one-to-one mapping of each SVG icon.

There has to be a more efficient way instead of having to copy this information _directly_ into a component.

**Comment by ricardoa-vega-stori** [comment]
I ended giving up on this component and doing my own version with a render function. This way, I only need to update the feather-icons package and use the new icons any time. Here's what I got:

```
<script>
const feather = require("feather-icons");

export default {
  props: {
    size: {
      required: false,
      type: String,
      default: "normal"
    },
    type: {
      required: true,
      type: String
    }
  },
  data() {
    return {
      defaultColor: "text-grey-darkest stroke-current"
    };
  },
  computed: {
    cssSizeClasses() {
      switch (this.size) {
      case "tiny": 
        return "h-4 w-4";
      case "small":
        return "h-6 w-6";
      case "normal":
        return "h-8 w-8";
      case "big":
        return "h-12 w-12";
      case "huge":
        return "h-16 w-16";
      case "giant":
        return "h-32 w-32";
      default:
        return "h-8 w-8";
      }
    }
  },
  render(createElement) {
    return createElement(
      "svg",
      {
        class: this.cssSizeClasses + " " + this.defaultColor,
        attrs: feather.icons[this.type].attrs,
        domProps: {
          innerHTML: feather.icons[this.type].contents
        }
      });
  }
};
</script>
```

I've added some classes and styling with tailwindcss, but basically, the render function is the important part. In this way, you can use any icon as soon as feather icons get updated :)

**Comment by jalcine** [comment]
Awesome. This helped me make one for TypeScript.

```html
<template>
  <svg v-bind="attrs" v-html="svgData" />
</template>

<script lang="ts">
import * as feather from 'feather-icons';
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class FeatherIcon extends Vue {
  @Prop(String) public type!: string;

  get svgData(): string {
    return feather.icons[this.type].contents;
  }

  get attrs(): object {
    return feather.icons[this.type].attrs;
  }
}
</script>
```

To be honest, this kind of logic _could_ replace the one currently existing.
