### ISSUE TITLE
Use functional components

### ISSUE THREAD

**Issue by egoist** [mage3k/vue-feather-icon#3]
Since all those `.vue` files only have `template`

**Comment by tthallos** [comment]
I have not use functional component before, any difference ?

**Comment by dealloc** [comment]
@mage3k functional components are components that don't manage any state and marking them as such will allow Vue to optimize them (as Vue can simply skip the entire re-render on state changes etc).

The official documentation on them is a bit "hidden" away, but can be found [here](https://vuejs.org/v2/guide/render-function.html#Functional-Components).

Another way to speed up rendering and make the components "lighter" would be to use [static components](https://vuejs.org/v2/guide/components.html#Cheap-Static-Components-with-v-once) which would tell Vue to cache them once they've been rendered.

I'm willing to make a PR with either option (you can't use both cached and function unfortunately, see [here](https://github.com/vuejs/vue/issues/5455) why) if you'd want.

**Comment by egoist** [comment]
@dealloc I actually made [vue-feather-icons](https://vue-feather-icons.netlify.com/) which is unnecessary after I made [svg-to-component-loader](https://github.com/egoist/svg-to-component-loader)

So I think I can close this now.
