### ISSUE TITLE
Issues using components with dynamic imports

### ISSUE THREAD

**Issue by morkro** [mage3k/vue-feather-icon#6]
I am experiencing issues using `vue-feather-icon` with dynamically imported components.

In my project, I make use of [code splitting](https://router.vuejs.org/en/advanced/lazy-loading.html) via dynamic imports:
```js
const router = new VueRouter({
  routes: [
    { path: '/foo', component: () => import('./Foo') }
  ]
})
```

Unfortunately, this approach doesn't work with `vue-feather-icon`. Using both [methods described in the README](https://github.com/mage3k/vue-feather-icon#usage), I get the following error:
<img width="525" alt="screen shot 2017-10-10 at 22 48 44" src="https://user-images.githubusercontent.com/2461956/31412832-905fefe8-ae0e-11e7-8499-4e13bf7601f7.png">
The rendering output is as follows:
<img width="482" alt="screen shot 2017-10-10 at 23 04 26" src="https://user-images.githubusercontent.com/2461956/31413035-6c1fe20e-ae0f-11e7-8d55-91fa61a28d2c.png">

I discovered two possible solutions to workaround/fix the issue:
Either dynamically import each icon independently. I don't really like that approach as I directly reference components in the library, but it seems to be the quickest solution for now.
```js
export default {
    name: 'Foo',

    components: {
      ActivityIcon: () => import('vue-feather-icon/components/activity.vue')
    }
}
```

Or dynamically import all components in `vue-feather-icon/plugin.js`. With that approach we could continue using the library as intended.
```js
module.exports = function(Vue) {
  Vue.component('feather-activity', () => import('./components/activity.vue'))
}
```

To be honest, I haven't tested if the latter introduces any other issues with projects not using dynamic imports, but I don't see why it should cause any.

What do you think? Is there maybe another solution I might not see?

**Comment by andresmrm** [comment]
Not sure if it's related with this issue, but I got the same error using the local component method from the [README](https://github.com/mage3k/vue-feather-icon#local-component).

*Fixed* it adding a `.default` to the imported component:

    import { Gitlab } from 'vue-feather-icon'
    export default {
      components: {
        gitlab: Gitlab.default
      }
    }

EDIT: `import gitlab from 'vue-feather-icon/components/gitlab'` also worked for me, and the built app.min.js is much smaller.

    import gitlab from 'vue-feather-icon/components/gitlab'
    export default {
      components: {
        gitlab: gitlab
      }
    }

**Comment by tthallos** [comment]
@andresmrm is right
In webpack

```
import gitlab from 'vue-feather-icon/components/gitlab'
```

Only gitlab icon be packaged into the bundle

**Comment by tthallos** [comment]
@morkro 
Foo.vue
```vue
import Activity from 'vue-feather-icon/components/activity.vue'

export default {
  name: 'foo',
  components: {
    Activity
  }
}
```

router.js
```
const router = new VueRouter({
  routes: [
    { path: '/foo', component: () => import('./Foo') }
  ]
})
```
you want use it like this?

**Comment by morkro** [comment]
I actually want to use it as a global component. So:

```js
// router.js
const router = new VueRouter({
  routes: [
    { path: '/foo', component: () => import('./Foo') }
  ]
})

// main.js
Vue.use(VueFeatherIcon)
```

And then `Foo.vue`:
```html
<template>
  <div>
    <feather-activity />
  </div>
</template>
```

**Comment by tthallos** [comment]
I guess this is caused by the code spling of webpack, You can use local component temporarily.

**Comment by shroy** [comment]
Not sure if this is related or I'm simply missing something. I am **not** using dynamic imports, however, I am receiving this very same error after attempting a basic global install. I am using webpack 3.4.1 with Vue 2.4.2.

`
  import VueFeatherIcon from 'vue-feather-icon'`
`  Vue.use(VueFeatherIcon)
`

**Comment by tthallos** [comment]
this repo is no longer maintained, you can try [vue-feather-icons](https://github.com/egoist/vue-feather-icons)
