### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by d8vjork** [mage3k/vue-feather-icon#8]
With `<feather-icon type="activity"></feather-icon>`  it returns: `<!--function (a, b, c, d) { return createElement(vm, a, b, c, d, true); }-->`

**Comment by shareiff** [comment]
I also have this issue I tried both importing as a local component and global. I noticed it when I upgraded webpack to 3.8. @d8vjork  are you using webpack at all?

**Comment by d8vjork** [comment]
@shareiff Yes, the vue-cli webpack template

**Comment by SacDin** [comment]
+1

**Comment by hyperupcall** [comment]
I get this also. I am also using Webpack, version 4.12.0. Has anyone found a way to resolve this issue?

**Comment by hyperupcall** [comment]
My apologies, I didn't read issue #6, which fixed the issue for me. I added .default to the components portion of my `.vue` file.

**Comment by tthallos** [comment]
this repo is no longer maintained, you can try [vue-feather-icons](https://github.com/egoist/vue-feather-icons)
